# Generated by Django 2.2.6 on 2019-10-31 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_address', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_amount', models.IntegerField()),
                ('item_sale_cost', models.FloatField()),
                ('item_pur_cost', models.FloatField()),
                ('last_update', models.DateTimeField()),
                ('item_description', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_role_id', models.CharField(choices=[('B', 'Billing'), ('P', 'Purchases'), ('S', 'Sales')], max_length=20)),
                ('login_username', models.CharField(max_length=15)),
                ('login_password', models.CharField(max_length=32)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=10)),
                ('role_desc', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAndPurchases',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchases')], max_length=1)),
                ('transaction_cus_id', models.CharField(max_length=15)),
                ('transaction_amt', models.FloatField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('bill_produced', models.BooleanField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_id', models.CharField(max_length=20)),
                ('per_name', models.CharField(max_length=20)),
                ('per_module', models.CharField(max_length=20)),
                ('per_role_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bill_total', models.FloatField()),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_status', models.CharField(default='Pending', max_length=30)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inventory')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SalesAndPurchases')),
            ],
        ),
    ]
