# Generated by Django 2.2.6 on 2019-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191105_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesandpurchases',
            name='transaction_amt',
            field=models.IntegerField(),
        ),
    ]
