# Generated by Django 2.2.6 on 2019-11-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191106_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_id',
            field=models.CharField(default='qaeuqkqplp', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='yjwgxzgpfr', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default='mzqusgintz', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_id',
            field=models.OneToOneField(default='jzzccsipcb', on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(default='asfqqkbopy', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesandpurchases',
            name='transaction_id',
            field=models.CharField(default='tmflvkyogy', max_length=10, primary_key=True, serialize=False),
        ),
    ]
