# Generated by Django 2.2.6 on 2019-11-06 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191106_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_id',
            field=models.CharField(default='qovmtfgent', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='upbxhgdjib', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default='npqaebuezm', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_id',
            field=models.OneToOneField(default='molxsvjwcp', on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(default='rntyfwkkph', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesandpurchases',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 5, 4, 55, 495959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesandpurchases',
            name='transaction_id',
            field=models.CharField(default='gxewmwpkpt', max_length=10, primary_key=True, serialize=False),
        ),
    ]
